name: Security Checks
on:
  pull_request:
    branches:
      - "main"

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  checkov:
    runs-on: ubuntu-latest
    name: checkov
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@v12.2407.0
        with:
          directory: .
  codeql:
    name: codeql
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'python' ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:${{matrix.language}}"

  get-action-details:
    name: get-action-details
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x

      - name: Add GitHub Action Details from PR
        uses: ActionsDesk/github-actions-details-action@v1.2.1
        with:
          search_token: ${{ secrets.GITHUB_TOKEN }}
          allow_list_path: github-actions-allow-list.yml
  cleanup-dir:
    if: contains("GHA request:", "${{ github.event.pull_request.title }}")
    needs: ["checkov", "codeql", "get-action-details"]
    name: Cleanup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Cleanup
        run: |
          rm -rf action_dir
      - name: Update PR
        uses: stefanzweifel/git-auto-commit-action@v4